version: '3.2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
      - backup:/backups/
    container_name: nextcloud-database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - traefik
    labels:
      - "docker-volume-backup.archive-pre=/bin/sh -c 'pg_dumpall -U ${POSTGRES_USER} > /backups/nextcloud_postgress.out'"
      - "docker-volume-backup.stop-during-backup=stopservice"   
  next:
    image: nextcloud
    hostname: next.ypstudio.ru
    restart: always
    ports:
      # - 8088:80
      - 80
    volumes:
      - nextcloud:/var/www/html
      - /mnt/Media:/data
    container_name: nextcloud-server
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.next.rule=Host(`next.ypstudio.ru`)"
      - "traefik.http.routers.next.entrypoints=websecure"
      - "traefik.http.services.next.loadbalancer.server.port=80"
      - "traefik.http.routers.next.tls.certresolver=myresolver"

      - "traefik.http.middlewares.next.headers.stsSeconds=15552000"
      - "traefik.http.middlewares.next.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.next.headers.stsPreload=true"
      - "traefik.http.middlewares.next.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.nextcloud-dav.replacepathregex.regex=^/.well-known/ca(l|rd)dav"
      - "traefik.http.middlewares.nextcloud-dav.replacepathregex.replacement=/remote.php/dav/"
      - "traefik.http.routers.next.middlewares=nextcloud-dav,next"
      
      - "docker-volume-backup.stop-during-backup=stopservice"
    networks:
      - traefik
volumes:
  db:
  nextcloud:
  backup:
    name: backup
    external: true
networks:
  traefik:
    name: traefik
